name: sleep_tracker
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  smooth_star_rating: any
  charts_flutter: ^0.9.0
  flutter_local_notifications: ^1.4.3
  shared_preferences: ^0.5.7
  sqflite: any
  path: any
  path_provider: any
  fluttertoast: ^4.0.1
  intro_slider: ^2.2.9
  percent_indicator: ^2.1.3
  url_launcher: ^5.4.5
  image_picker: ^0.6.6+1
  get_it: ^4.0.2
  liquid_progress_indicator: ^0.3.2
  google_fonts: ^1.1.0
  shimmer: ^1.1.1
  flutter_xlider: ^3.4.0
  bottom_navy_bar: any
  step_progress_indicator: ^0.2.3+6


dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  - assets/images/cardSleepToday.png
  - assets/images/communityBg.png
  - assets/images/twitter.png
  - assets/images/facebook.png
  - assets/images/instagram.png
  - assets/images/nodata.png
  - assets/images/nodatapad.png
  - assets/images/lack_of_sleep.png
  - assets/images/sleepTracker.png
  - assets/images/avatar.png
  - assets/images/logo.png
  - assets/images/today_sleep.png
  - assets/images/tip_day.png
  - assets/images/rain_drops.png
  - assets/images/soda.png
  - assets/images/beans.png
  - assets/images/juice.png
  - assets/images/tea.png
  - assets/images/manual.png



  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:

  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
